### ISSUE TITLE
Incoming Calls not connecting but rings once or doesn’t ring at all but registers a call coming through

### ISSUE THREAD

**Issue by mustang31489** [grahambrown11/buzz-star#42] opened 2023-07-01 05:47 UTC
So how do we make sure that buzz isn’t idle resulting in dropped calls when on or off auto answer for our call center employees?

**Comment by grahambrown11** [comment] 2023-07-02 13:46
duplicate of #41

**Closed as completed by grahambrown11** 2023-07-02 13:46 UTC
